### ISSUE TITLE
Installation (final stage) error 

### ISSUE THREAD

**Issue by aaronlhe** [firedrakeproject/firedrake#1211]
Hi there, 

I have followed the instructions at https://www.firedrakeproject.org/download.html in order to install firedrake on an Ubuntu 16.04 desktop. I am running into this error at the final stage of installation....log file is as attached.

I would sincerely appreciate any pointers... this looks like an awesome library to be working with. 
```
 *******************************************************************************
             UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
    -------------------------------------------------------------------------------
    Error during download/extract/detection of CHACO:
    Unable to download package CHACO from: http://ftp.mcs.anl.gov/pub/petsc/externalpackages/Chaco-2.2-p2.tar.gz
    * If URL specified manually - perhaps there is a typo?
    * If your network is disconnected - please reconnect and rerun ./configure
    * Or perhaps you have a firewall blocking the download
    * You can run with --with-packages-dir=/adirectory and ./configure will instruct you what packages to download manually
    * or you can download the above URL manually, to /yourselectedlocation/Chaco-2.2-p2.tar.gz
      and use the configure option:
      --download-chaco=/yourselectedlocation/Chaco-2.2-p2.tar.gz
    Unable to download package CHACO from: ftp://ftp.mcs.anl.gov/pub/petsc/externalpackages/Chaco-2.2-p2.tar.gz
    * If URL specified manually - perhaps there is a typo?
    * If your network is disconnected - please reconnect and rerun ./configure
    * Or perhaps you have a firewall blocking the download
    * You can run with --with-packages-dir=/adirectory and ./configure will instruct you what packages to download manually
    * or you can download the above URL manually, to /yourselectedlocation/Chaco-2.2-p2.tar.gz
      and use the configure option:
      --download-chaco=/yourselectedlocation/Chaco-2.2-p2.tar.gz
    *******************************************************************************

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-dc25yyo5-build/setup.py", line 302, in <module>
        **metadata)
      File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-dc25yyo5-build/setup.py", line 218, in run
        config(prefix, self.dry_run)
      File "/tmp/pip-dc25yyo5-build/setup.py", line 148, in config
        if status != 0: raise RuntimeError(status)
    RuntimeError: 256
    Running setup.py install for petsc: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-dc25yyo5-build
Command "/home/aaronlhe/Downloads/firedrake/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-dc25yyo5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s000u03t-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/aaronlhe/Downloads/firedrake/include/site/python3.5/petsc" failed with error code 1 in /tmp/pip-dc25yyo5-build/
Exception information:
Traceback (most recent call last):
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/aaronlhe/Downloads/firedrake/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-dc25yyo5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s000u03t-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/aaronlhe/Downloads/firedrake/include/site/python3.5/petsc" failed with error code 1 in /tmp/pip-dc25yyo5-build/

2018-03-29 14:01:19,761 INFO   

Install log saved in firedrake-install.log
Cleaning up...
  Removing source in /tmp/pip-dc25yyo5-build
Command "/home/aaronlhe/Downloads/firedrake/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-dc25yyo5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s000u03t-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/aaronlhe/Downloads/firedrake/include/site/python3.5/petsc" failed with error code 1 in /tmp/pip-dc25yyo5-build/
Exception information:
Traceback (most recent call last):
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/aaronlhe/Downloads/firedrake/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/aaronlhe/Downloads/firedrake/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-dc25yyo5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s000u03t-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/aaronlhe/Downloads/firedrake/include/site/python3.5/petsc" failed with error code 1 in /tmp/pip-dc25yyo5-build/

2018-03-29 14:01:19,761 INFO   

Install log saved in firedrake-install.log
```
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/1858765/firedrake-install.log)

**Comment by wence-** [comment]
Hi, this looks like the step that installs PETSc failed when downloading Chaco from `http://ftp.mcs.anl.gov/pub/petsc/externalpackages/Chaco-2.2-p2.tar.gz`.

This might have been a network issue at your end, but when I try, it looks like the ftp.mcs.anl.gov site is currently inaccessible.

So, it looks like you did nothing wrong, it's just that a remote site has no internet connectivity.

I've emailed the PETSc folks to see if they have any idea, and will update this issue when I get a response.

**Comment by aaronlhe** [comment]
Thank you very much Wence. Much appreciated, and do let me know if there s anything I can do to help.

**Comment by wence-** [comment]
Argonne appear to have fixed their problems.

If you remove the `firedrake` directory that the installation process created, and start again with `firedrake-install`, I hope everything works.

Do let us know if there are any further issues.

Thanks!

**Comment by aaronlhe** [comment]
Hi Lawrence, 

I have tried again this morning but its still unsuccessful, stuck at another step (chaco now downloads successfully). However it runs into an error at running configure on PNETCDF, (log file attached) ...

    Specified MPI C compiler "/usr/bin/mpicc" cannot be found
    Parallel netCDF requires a working MPI C compiler. Please specify the
    location of an MPI C compiler, either in the MPICC environment variable
    or through --with-mpi configure flag. Abort.

When I key in 'mpicc' into my terminal, ubuntu seems to recognize this command (although no arguments so it returns 'gcc fatal error no input files') , and when i do 

    sudo dpkg -l | grep mpi

I get the following return:

![untitled](https://user-images.githubusercontent.com/19923777/38157865-af32347c-34bd-11e8-972f-04e06265fa17.png)

I'm really new when it comes to mpi , and am really quite lost. Do i have to install additional depencies prior to running python3 firedrake-install ? 

Really appreciate your advise. Thanksss

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/1865046/firedrake-install.log)

**Comment by rckirby** [comment]
Happened on my Mac as well, FYI

**Comment by aaronlhe** [comment]
Does anyone have a solution for this?

**Comment by wence-** [comment]
Hopefully we'll be able to debug it this coming week. I think everyone is away over Easter at the moment, so responses might not be immediate.

**Comment by stephankramer** [comment]
I've hit the same error, both on an Ubuntu 16.04 system and on a more 
recent Debian testing.

It seems there's some obscure bug in pnetcdf where if you specify 
CC=/usr/bin/mpicc (including the path) on its configure, it gets 
confused, whereas CC=mpicc works fine. The CC=/usr/bin/mpicc is 
something that originates in the petsc python package (it automatically 
adds a --with-cc to petsc's configure). As a work-around, if you set

export PETSC_CONFIGURE_OPTIONS='--with-cc=mpicc'

before running the install script, things work again for me (setting 
MPICC=mpicc may also work)

Cheers
Stephan

**Comment by wence-** [comment]
Thanks @stephankramer, I'll report a bug to PETSc.

**Comment by rckirby** [comment]
Ok, on my Mac,
export PETSC_CONFIGURE_OPTIONS='--with-cc=mpicc'
followed by
python3 ./firedrake-install

works on PETSc.  However, now the installer dies building libspatialindex,
relevant error seems to be in using glibtoolize -- it can't find sed. Log
attached

2018-04-04 11:35:26,666 DEBUG  Running command 'git clean -f -x -d'
2018-04-04 11:35:26,679 DEBUG
2018-04-04 11:35:26,679 DEBUG  Running command 'sed -i -e /^SUBDIRS/s/
test// Makefile.am'
2018-04-04 11:35:26,685 DEBUG
2018-04-04 11:35:26,686 DEBUG  Running command './autogen.sh'
2018-04-04 11:35:33,093 DEBUG  Running aclocal
Running libtoolize
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No
such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No
such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No
such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No
such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No
such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No
such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No
such file or directory
Running automake

**Comment by wence-** [comment]
@rckirby can you run `brew doctor` and see what it says?

**Comment by rckirby** [comment]
Please note that these warnings are just used to help the Homebrew
maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcrypto.0.9.8.dylib
  /usr/local/lib/libcrypto.dylib
  /usr/local/lib/libklcskca.dylib
  /usr/local/lib/libklcsrt.dylib
  /usr/local/lib/libklcsstd.dylib
  /usr/local/lib/libklcstr.dylib
  /usr/local/lib/libklmspack.0.1.0.dylib
  /usr/local/lib/libklmspack.0.dylib
  /usr/local/lib/libklmspack.dylib
  /usr/local/lib/libssl.0.9.8.dylib
  /usr/local/lib/libssl.dylib
  /usr/local/lib/libz.1.2.5.dylib
  /usr/local/lib/libz.1.dylib
  /usr/local/lib/libz.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend
on
those kegs to fail to run properly once built. Run `brew link` on these:
  superlu43
  mercurial

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuPro-W3
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuPro-W6
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuProN-W3
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuProN-W6
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuStd-W8
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuStdN-W8
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMaruPro-W4
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMaruProN-W4
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinPro-W3
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinPro-W6
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinProN-W3
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinProN-W6
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraginoSansGB-W3
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraginoSansGB-W6
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/YuGo-Bold
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/YuGo-Medium
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/YuMin-Demibold
  /usr/local/share/ghostscript/9.16/Resource/CIDFont/YuMin-Medium

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install fribidi libidn2 libmikmod libogg libunistring libvorbis
python@2

Run `brew missing` for more details.


On Wed, Apr 4, 2018 at 11:50 AM, Lawrence Mitchell <notifications@github.com

**Comment by wence-** [comment]
Hmph.

Can you try:

````
brew update
brew uninstall libtool
brew install libtool
```

And then try again.  Sometimes homebrew seems to get in a mess.

**Comment by rckirby** [comment]
Done, brilliant.  Thanks!

On Wed, Apr 4, 2018 at 12:08 PM, Lawrence Mitchell <notifications@github.com

**Comment by aaronlhe** [comment]
I am still stuck at the same error: mpicc part where the installation still can't find the MPI C compiler.  Running on Ubuntu 16.04 LTS , and I did export the PETSC_CONFIGURE_OPTIONS as suggested by Stephen. I really don't know how else to proceed.

**Comment by wence-** [comment]
Can you please upload the latest `firedrake-install.log`?

I hope the root cause will be fixed soon (pnetcdf have fixed their configure script), once PETSc incorporate new changes.  But we'd like to get you up and running before then!

**Comment by aaronlhe** [comment]
Hi Lawrence, 
I've attached it herein... my latest attempt was , in addition to doing the env var export, to do the installation in the root directory (last resort, out of ideas kind of thing)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/1880076/firedrake-install.log)

Thanks a bunch, really.

**Comment by wence-** [comment]
OK, I see.  Something isn't working right.  But, this is an error that lots of people will have, so I made a fix in firedrake-install which should work.  At least, it fixed the problem for me.

Can you please download firedrake-install from https://raw.githubusercontent.com/firedrakeproject/firedrake/fix/install-pnetcdf/scripts/firedrake-install

and run that.  There should be no need to run things as root, or in a root directory.

**Comment by aaronlhe** [comment]
Thanks Lawrence, it now installs flawlessly. =) 

However when i ran the make alltest, i got this error

    Building extension modules
    Traceback (most recent call last):
    File "setup.py", line 31, in <module>
     import versioneer
     File "/home/firedrake/firedrake/src/firedrake/versioneer.py", line 1658
    file=sys.stderr)
        ^
    SyntaxError: invalid syntax
    Linting firedrake codebase
    /usr/bin/python: No module named flake8 
    Makefile:8: recipe for target 'lint' failed
    make: *** [lint] Error 1

Hopefully it does not break firedrake, and i will be testing it out with some of your examples later; will get back to you soon

**Comment by wence-** [comment]
Good news!  I'll make sure that that fix is merged for everyone soon.

This new error looks like you typed `make alltest` before activating the `venv`.  The installation script puts firedrake (and its dependencies) in an [isolated environment](https://docs.python.org/3/library/venv.html) so that it doesn't interact badly with anything else you might have installed.

A consequence of this is that you must "activate" this environment in the shell before attempting to run Firedrake (or relevant dependencies).  You do this by running `source /home/firedrake/firedrake/bin/activate`.

I'll close this issue, since the initial problem was fixed.  Please open any new issues if you have further problems.

Thanks!
