### ISSUE TITLE
Installation error on MacBook pro

### ISSUE THREAD

**Issue by Wajiha11** [firedrakeproject/firedrake#2002]
Hello Firedrake team,

I am trying to install firedrake on my Macbook pro and I have checked the requirements like Homebrew installation and Python version for the installation. Unfortunately, I am facing some kind of errors that I am unable to understand. Could you please take a look at the log file and help me
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6116891/firedrake-install.log)
 with the installation of Firedrake?

Thank you for your help.

Regards,
Wajiha

**Comment by JDBetteridge** [comment]
It looks like something is going wrong when you create a venv, can you successfully run:
```
python3 -m venv test_venv
```
?

If this fails, its possible there is something wrong with your Python install. Ensure you are using the python installed by homebrew, not the system python and if you are try reinstalling python with homebrew.

**Comment by Wajiha11** [comment]
Hello, 


Thank you for your reply. I have run the command and here is what I got.

<img width="682" alt="Screenshot 2021-03-11 at 11 28 50" src="https://user-images.githubusercontent.com/71877393/110781013-410ef200-825d-11eb-988d-37c51c2b414f.png">


Regards,
Wajiha

**Comment by JDBetteridge** [comment]
If you now activate that test environment and try to execute what the install script did, does it error?
```
source test_venv/bin/activate
python -Im ensurepip --upgrade --default-pip
```

**Comment by Wajiha11** [comment]
<img width="815" alt="Screenshot 2021-03-11 at 11 55 06" src="https://user-images.githubusercontent.com/71877393/110783679-a9ab9e00-8260-11eb-9bed-19db4d156a2a.png">

**Comment by JDBetteridge** [comment]
I'm a bit stumped, as we've essentially done exactly what the install script does and not hit any problems. Perhaps you could try re-running the install script to see if you hit the same issue again

**Comment by Wajiha11** [comment]
Hi, I ran the command and I still got the error.

![image](https://user-images.githubusercontent.com/71877393/110787368-25a7e500-8265-11eb-9b13-2ce943d6d99a.png)

**Comment by Wajiha11** [comment]
Hello,

I found that the problem was related to the python version which my Mac was using by default. After I fixed that, I was able to install firedrake. I just want you to take a look at the test that I performed after installation and confirm if it is good or not.

<img width="1792" alt="Screenshot 2021-03-12 at 13 25 41" src="https://user-images.githubusercontent.com/71877393/110947630-5016a280-8338-11eb-9238-435a056c0eb7.png">


I am very thankful for your kind support in this regard.

**Comment by wence-** [comment]
That looks pretty good to me, thanks for the update!

**Comment by klaatujk** [comment]
> Hello,
> 
> I found that the problem was related to the python version which my Mac was using by default. After I fixed that, I was able to install firedrake. I just want you to take a look at the test that I performed after installation and confirm if it is good or not.
> 
> <img alt="Screenshot 2021-03-12 at 13 25 41" width="1792" src="https://user-images.githubusercontent.com/71877393/110947630-5016a280-8338-11eb-9238-435a056c0eb7.png">
> 
> I am very thankful for your kind support in this regard.

I may have the same issue with you. Could you let me know how did you fix it from default to the python version worked?
I have changed paths several times, but still failed.

**Comment by Wajiha11** [comment]
Hi Klaatujk,


1st step is to install Homebrew. Try downloading the files by using the instruction explained on homebrew:
https://brew.sh/

Once you have installed Homebrew then you need to install the right version of python 3 by using the following command:
brew install python3

Then you can make it default, try using the procedure explained on this website:
https://dev.to/malwarebo/how-to-set-python3-as-a-default-python-version-on-mac-4jjf

Then run the test case by using the procedure explained on the firedrake site:
https://www.firedrakeproject.org/download.html

I hope it will solve the problem.

Regards,
Wajiha

**Comment by klaatujk** [comment]
Hi Wajiha

Thanks for your response.

I followed your guidance and tried to install firedrake with python3.8 installed from Homebrew on M1 MacBook.
But still failed in installing MPICH.

I will try it with python3.6 < 3.8.

Regards
Sooyoul
http://www.civil.kumamoto-u.ac.jp/sooyoulkim/
https://www.researchgate.net/profile/Sooyoul_Kim
