### ISSUE TITLE
BUG: spurious arity errors in 2 forms with conditionals

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#3984]
Consider the following code
```
from firedrake import *
mesh = UnitSquareMesh(2, 2)
V = VectorFunctionSpace(mesh, "CG", 1)
W = FunctionSpace(mesh, "CG", 1)
Z = V*W
ztst = TestFunction(Z)
v, _ = split(ztst)
z = Function(Z)
u, p = split(z)

unorm = sqrt(dot(u, u))
c_t = conditional(unorm<0, 0, unorm)
F = dot(ztst, z)*dx + c_t * dot(v, u) * dx
assemble(derivative(F, z))
```
This produces the - I believe - spurious error:
```
Traceback (most recent call last):
  File "/home/firedrake/firedrake/src/thetis/examples/discrete_turbines/tst2.py", line 14, in <module>
    assemble(derivative(F, z))
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/assembly.py", line 30, in wrapper
    output = assemble(form, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 134, in assemble
    return get_assembler(expr, *args, **kwargs).assemble(tensor=tensor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 992, in assemble
    tensor = self.allocate()
             ^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 1330, in allocate
    self._make_maps_and_regions())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 1359, in _make_maps_and_regions
    elif any(local_kernel.indices == (None, None) for assembler in self._all_assemblers for local_kernel, _ in assembler.local_kernels):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 1359, in <genexpr>
    elif any(local_kernel.indices == (None, None) for assembler in self._all_assemblers for local_kernel, _ in assembler.local_kernels):
                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 1069, in local_kernels
    kernels = tsfc_interface.compile_form(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/pyop2/caching.py", line 550, in wrapper
    value = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/pyop2/caching.py", line 550, in wrapper
    value = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 220, in compile_form
    tsfc_kernel = TSFCKernel(
                  ^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 95, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/pyop2/caching.py", line 550, in wrapper
    value = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/pyop2/caching.py", line 550, in wrapper
    value = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/tsfc/driver.py", line 67, in compile_form
    fd = ufl_utils.compute_form_data(form, complex_mode=complex_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/tsfc/ufl_utils.py", line 56, in compute_form_data
    fd = ufl_compute_form_data(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/compute_form_data.py", line 423, in compute_form_data
    check_form_arity(preprocessed_form, self.original_form.arguments(), complex_mode)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/check_arities.py", line 213, in check_form_arity
    check_integrand_arity(itg.integrand(), arguments, complex_mode)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/check_arities.py", line 194, in check_integrand_arity
    arg_tuples = map_expr_dag(rules, expr, compress=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 35, in map_expr_dag
    (result,) = map_expr_dags(
                ^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 103, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/check_arities.py", line 60, in sum
    f"Adding expressions with non-matching form arguments {_afmt(a)} vs {_afmt(b)}."
                                                           ^^^^^^^^
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/check_arities.py", line 20, in _afmt
    arg, conj = atuple
    ^^^^^^^^^
```
This comes up in a number of tests in Thetis, see https://github.com/thetisproject/thetis/actions/runs/12837587893/job/35801573679
(this is after fixing the cases where 1-forms were being assembled into a Function instead of a Cofunction, see https://github.com/thetisproject/thetis/pull/388). The commonality between these tests is that they all have a conditional as part of the expression. These errors occur in the current (firedrake-vanilla) container, but not in firedrake-vanilla:2024-10

**Comment by connorjward** [comment]
@pbrubeck do you have any ideas?

**Comment by pbrubeck** [comment]
@stephankramer the fix is merged. Could you confirm this fixes the broken tests in Thetis?

**Comment by stephankramer** [comment]
Many thanks @pbrubeck! This fixes this issue for the 7 failing tests indeed but 2 of these are still failing with another issue, #3990. I believe this issue can be closed.
